language: node_js
node_js:
  - "0.10"
before_script:
  - "npm install -g codeclimate-test-reporter"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb startscript: "npm run test-cov"
after_script: "cat coverage/lcov.info | codeclimate"
addons:
  code_climate:
    repo_token: 4a4f5e5ae1b2019ed69267793ab2c8a3e476745cb4d133eae08d44cfdb6325ec
