#!/bin/sh
./node_modules/karma/bin/karma start karma.conf.js --single-run --browsers Firefox
./node_modules/.bin/mocha --require ./babel.js --require src/__tests__/testdom.js --compilers jsx:babel/register ./src/__tests__/*.mocha.*