const KEY_CODE_LEFT      = 37;
const KEY_CODE_RIGHT     = 39;
const KEY_CODE_DELETE    = 48;
const KEY_CODE_BACKSPACE = 8;
const KEY_CODE_COMMA     = 188;
const KEY_CODE_TAB       = 9;
const KEY_CODE_ESCAPE    = 27;

module.exports = {
  LEFT_ARROW: KEY_CODE_LEFT,
  RIGHT_ARROW: KEY_CODE_RIGHT,
  DELETE: KEY_CODE_DELETE,
  BACKSPACE: KEY_CODE_BACKSPACE,
  COMMA: KEY_CODE_COMMA,
  TAB: KEY_CODE_TAB,
  ESCAPE: KEY_CODE_ESCAPE
};
