const KEY_CODE_LEFT = 37;
const KEY_CODE_RIGHT = 39;
const KEY_CODE_DELETE = 48;
const KEY_CODE_BACKSPACE = 8;

module.exports = {
  LEFT_ARROW: KEY_CODE_LEFT,
  RIGHT_ARROW: KEY_CODE_RIGHT,
  DELETE: KEY_CODE_DELETE,
  BACKSPACE: KEY_CODE_BACKSPACE
};
